---
- name: Get Azure ad sp info
  hosts: localhost
  connection: local
  tasks:
    - name: get ad sp info
      azure_rm_adserviceprincipal_info:
        app_id: "{{ app_id }}"
        tenant: "{{ tenant_id }}"
